# Site settings
title: Developer Winterlood
description: This is winterlood's portpolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: WINTERLOOD
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Software Developer
email: king199777@gmail.com
twitter_username: X
github_username:  winterlood
gplus_username:  winterlood

# Google-analytics
google-analytics:
  id: "king199777@gamil.com"

exclude: ['package.json', 'src' , 'node_modules']
